name: Resilience Mirror IPFS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  mirror:
    runs-on: ubuntu-latest
    env:
      WEB3_STORAGE_TOKEN: ${{ secrets.WEB3_STORAGE_TOKEN }}
      PINATA_JWT: ${{ secrets.PINATA_JWT }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install PyNaCl

      - name: Verify ledger
        run: |
          test -f chain/CHAIN.jsonl || (echo "::error ::Missing chain/CHAIN.jsonl"; exit 1)
          python chain/chain_verify.py

      - name: Upload ledger artifact
        uses: actions/upload-artifact@v4
        with:
          name: fabric-ledger-${{ github.sha }}
          path: chain/CHAIN.jsonl
          if-no-files-found: error

      - name: Pin to IPFS (web3.storage)
        if: ${{ env.WEB3_STORAGE_TOKEN != '' }}
        shell: bash
        run: |
          set -e
          RESP=$(curl -sS -X POST https://api.web3.storage/upload \
            -H "Authorization: Bearer ${WEB3_STORAGE_TOKEN}" \
            -F file=@chain/CHAIN.jsonl)
          CID=$(echo "$RESP" | python -c 'import sys,json; print(json.load(sys.stdin).get("cid",""))')
          if [ -n "$CID" ]; then
            echo "CID=$CID" >> "$GITHUB_ENV"
            {
              echo "## IPFS (web3.storage)"
              echo "- CID: \`$CID\`"
              echo "- Gateway: https://w3s.link/ipfs/$CID"
            } >> "$GITHUB_STEP_SUMMARY"
          else
            echo "::warning ::web3.storage did not return a CID"
          fi

      - name: Pin to IPFS (Pinata)
        if: ${{ env.PINATA_JWT != '' }}
        shell: bash
        run: |
          set -e
          RESP=$(curl -sS -X POST 'https://api.pinata.cloud/pinning/pinFileToIPFS' \
            -H "Authorization: Bearer ${PINATA_JWT}" \
            -F file=@chain/CHAIN.jsonl)
          PINATA_CID=$(echo "$RESP" | python -c 'import sys,json; print(json.load(sys.stdin).get("IpfsHash",""))')
          if [ -n "$PINATA_CID" ]; then
            echo "PINATA_CID=$PINATA_CID" >> "$GITHUB_ENV"
            {
              echo "## IPFS (Pinata)"
              echo "- CID: \`$PINATA_CID\`"
              echo "- Gateway: https://gateway.pinata.cloud/ipfs/$PINATA_CID"
            } >> "$GITHUB_STEP_SUMMARY"
          else
            echo "::warning ::Pinata did not return a CID"
          fi

      - name: Commit CID file
        if: ${{ env.CID != '' || env.PINATA_CID != '' }}
        shell: bash
        run: |
          set -e
          mkdir -p chain
          {
            echo "Last refresh: $(date -u +%FT%TZ)"
            [ -n "${CID:-}" ] && echo "web3.storage: ${CID}"
            [ -n "${PINATA_CID:-}" ] && echo "pinata: ${PINATA_CID}"
          } > chain/CID.txt
          if ! git diff --quiet -- chain/CID.txt 2>/dev/null; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add chain/CID.txt
            git commit -m "chore(chain): update latest IPFS CID [skip ci]"
            git push
          else
            echo "CID.txt unchanged; skipping commit."
          fi
