name: Verify Fabric Chain

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Fail fast if the ledger file is missing
      - run: test -f chain/CHAIN.jsonl || (echo "::error ::Missing chain/CHAIN.jsonl"; exit 1)

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install PyNaCl

      # Verify the chain integrity
      - name: Verify ledger
        run: python chain/chain_verify.py

      # Summarize latest block (index/hash/merkle/timestamp) in the job summary
      - name: Summarize latest block
        run: |
          python - <<'PY'
          import json, pathlib, os
          p = pathlib.Path("chain/CHAIN.jsonl")
          lines = [l for l in p.read_text(encoding="utf-8").splitlines() if l.strip()]
          b = json.loads(lines[-1])
          idx = b.get("index"); h = b.get("block_hash"); mr = b.get("merkle_root"); ts = b.get("timestamp"); notes = b.get("notes","")
          summary = f"""## Fabric Chain — Latest Block

          - **Index:** `{idx}`
          - **Hash:** `{h}`
          - **Merkle root:** `{mr}`
          - **Timestamp (UTC):** `{ts}`
          - **Notes:** {notes if notes else "_(none)_"}

          Verify locally:
          \`\`\`bash
          python3 chain/chain_verify.py
          tail -n 1 chain/CHAIN.jsonl
          \`\`\`
          """
          with open(os.environ["GITHUB_STEP_SUMMARY"], "a", encoding="utf-8") as f:
            f.write(summary)
          PY

      # Upload ledger as a run artifact (downloadable)
      - name: Upload ledger artifact
        uses: actions/upload-artifact@v4
        with:
          name: fabric-ledger-${{ github.sha }}
          path: chain/CHAIN.jsonl
          if-no-files-found: error
